### ISSUE TITLE
panic: runtime error: slice bounds out of range [1:0]

### ISSUE THREAD

**Issue by orestonce** [yapingcat/gomedia#13]
* 复现方法: go run main.go
[d3.zip](https://github.com/yapingcat/gomedia/files/8953726/d3.zip)
* 完整堆栈信息:
````
panic: runtime error: slice bounds out of range [1:0]

goroutine 1 [running]:
github.com/yapingcat/gomedia/codec.GetPPSId({0xc0000aa036, 0xc0000a44e0, 0x0})
	/root/go/pkg/mod/github.com/yapingcat/gomedia@v0.0.0-20220621143944-d00dc3e02cdc/codec/h264.go:227 +0x93
github.com/yapingcat/gomedia/codec.GetPPSIdWithStartCode({0xc0000aa036, 0xc000196000, 0x3fa})
	/root/go/pkg/mod/github.com/yapingcat/gomedia@v0.0.0-20220621143944-d00dc3e02cdc/codec/h264.go:223 +0xd0
github.com/yapingcat/gomedia/mp4.(*Movmuxer).writeH264.func1({0xc0000b9c22, 0x600, 0x3de})
	/root/go/pkg/mod/github.com/yapingcat/gomedia@v0.0.0-20220621143944-d00dc3e02cdc/mp4/mp4muxer.go:436 +0x7ad
github.com/yapingcat/gomedia/codec.SplitFrameWithStartCode({0xc0000b9c22, 0x8, 0x3de}, 0xc0001cf9a8)
	/root/go/pkg/mod/github.com/yapingcat/gomedia@v0.0.0-20220621143944-d00dc3e02cdc/codec/util.go:58 +0x24f
github.com/yapingcat/gomedia/mp4.(*Movmuxer).writeH264(0x7f87e56d0e00, 0x7f87e56d0d00, {0xc0000b9c22, 0x4148ab, 0x7f87e56d0d00}, 0xc0001cfa40, 0x7f87e58bdfff)
	/root/go/pkg/mod/github.com/yapingcat/gomedia@v0.0.0-20220621143944-d00dc3e02cdc/mp4/mp4muxer.go:415 +0xa5
github.com/yapingcat/gomedia/mp4.(*Movmuxer).Write(0xc00008e180, 0x0, {0xc0000b9c22, 0x8, 0x3de}, 0x64, 0xc000000340)
	/root/go/pkg/mod/github.com/yapingcat/gomedia@v0.0.0-20220621143944-d00dc3e02cdc/mp4/mp4muxer.go:306 +0x145
main.main.func1.1({0xc0000b9c22, 0x8, 0x3de})
	/tmp/d3/d3/main.go:50 +0x90
github.com/yapingcat/gomedia/codec.SplitFrameWithStartCode({0xc0000b9c22, 0x8, 0x3de}, 0xc0001cfb38)
	/root/go/pkg/mod/github.com/yapingcat/gomedia@v0.0.0-20220621143944-d00dc3e02cdc/codec/util.go:58 +0x24f
main.main.func1(0x7f880c1ef5b8, {0xc0000b9c22, 0x56bde0, 0xc00024f6b0}, 0x0, 0x10100c0000a4138)
	/tmp/d3/d3/main.go:45 +0x9b
github.com/yapingcat/gomedia/mpeg2.(*TSDemuxer).splitH26XFrame(0xc0001cfec0, 0xc0000b4000)
	/root/go/pkg/mod/github.com/yapingcat/gomedia@v0.0.0-20220621143944-d00dc3e02cdc/mpeg2/ts-demuxer.go:209 +0x22f
github.com/yapingcat/gomedia/mpeg2.(*TSDemuxer).doVideoPesPacket(0x4e0f40, 0xc0000b4000, 0x40)
	/root/go/pkg/mod/github.com/yapingcat/gomedia@v0.0.0-20220621143944-d00dc3e02cdc/mpeg2/ts-demuxer.go:167 +0x1a5
github.com/yapingcat/gomedia/mpeg2.(*TSDemuxer).Input(0xc0001cfec0, {0x4e0f00, 0xc00024f560})
	/root/go/pkg/mod/github.com/yapingcat/gomedia@v0.0.0-20220621143944-d00dc3e02cdc/mpeg2/ts-demuxer.go:122 +0xa3e
main.main()
	/tmp/d3/d3/main.go:61 +0x376
exit status 2

````

**Comment by yapingcat** [comment]
<img width="456" alt="wecom-temp-6f24ba92c68b5b00838cd35523d5ad17" src="https://user-images.githubusercontent.com/32125710/174930870-d5505822-87a1-4122-b789-fc7457a73661.png">


muxer.WriteTrailer()不应该放在循环里面，对于一个mp4文件，WriteTrailer 只能调用一次

**Comment by orestonce** [comment]
原来如此
