### ISSUE TITLE
rtmp server示例代码引发Panic

### ISSUE THREAD

**Issue by Mr3h1v** [yapingcat/gomedia#142]
1. 示例程序错误提示
```
$ go run example_rtmp_server.go
publish start
play start
ready to play
panic: OUT OF RANGE

goroutine 52 [running]:
github.com/yapingcat/gomedia/go-codec.(*BitStream).GetBit(...)
        ~/go/src/gomedia/go-codec/bitstream.go:90
github.com/yapingcat/gomedia/go-codec.(*BitStream).ReadUE(0xc000095a00?)
        ~/go/src/gomedia/go-codec/bitstream.go:152 +0xf0
github.com/yapingcat/gomedia/go-codec.(*H264HrdParameters).Decode(0xc000095c58, 0x10dfd58?)
        ~/go/src/gomedia/go-codec/h264.go:567 +0xe5
github.com/yapingcat/gomedia/go-codec.(*H264VuiParameters).Decode(0xc000095c28, 0x3?)
        ~/go/src/gomedia/go-codec/h264.go:529 +0x237
github.com/yapingcat/gomedia/go-codec.(*SPS).Decode(0xc000095b58, 0xc000095b20)
        ~/go/src/gomedia/go-codec/h264.go:143 +0x86a
github.com/yapingcat/gomedia/go-codec.CreateH264AVCCExtradata({0xc000010198, 0x1, 0x74373?}, {0xc0000101b0, 0x1, 0x123cfc0?})
        ~/go/src/gomedia/go-codec/h264.go:356 +0x705
github.com/yapingcat/gomedia/go-flv.(*AVCMuxer).Write(0xc0000020c0, {0xc000604000?, 0x0?, 0x0?}, 0x2904, 0x28b0)
        ~/go/src/gomedia/go-flv/flv-muxer.go:137 +0x436
github.com/yapingcat/gomedia/go-rtmp.(*RtmpServerHandle).WriteVideo(0xc000116100, 0x2d?, {0xc000604000, 0x74373, 0x74373}, 0x4b4f20?, 0xc0?)
        ~/go/src/gomedia/go-rtmp/server.go:249 +0x310
github.com/yapingcat/gomedia/go-rtmp.(*RtmpServerHandle).WriteFrame(0xc000116100?, 0x0, {0xc000604000, 0x74373, 0x74373}, 0x2904?, 0x28b0?)
        ~/go/src/gomedia/go-rtmp/server.go:214 +0x125
main.(*MediaSession).sendToClient(0xc0002fc100)
        ~/go/src/gomedia/example_rtmp_server.go:276 +0x23d
created by main.(*MediaSession).init.func4
        ~/go/src/gomedia/example_rtmp_server.go:193 +0x365
exit status 2
```

2. 视频文件信息与推流命令
```
$ ffprobe -hide_banner sample.mp4
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'sample.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf56.25.101
  Duration: 00:00:30.00, start: 0.000000, bitrate: 6058 kb/s
  Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], 5860 kb/s, 24 fps, 24 tbr, 12288 tbn (default)
      Metadata:
        handler_name    : VideoHandler
        vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, 5.1, fltp, 192 kb/s (default)
      Metadata:
        handler_name    : SoundHandler
        vendor_id       : [0][0][0][0]

ffmpeg -re -stream_loop -1 -i sample.mp4 -c copy -f flv -muxrate 6000k rtmp://127.0.0.1/live/livestream
```

3. 拉流指令
``` 
ffplay rtmp://127.0.0.1/live/livestream
```

异常表现，示例程序启动后，只推流没有问题，一旦有客户端开始拉流就会Panic退出。

**Comment by yapingcat** [comment]
测试的mp4文件提供一下

**Comment by Mr3h1v** [comment]
> 测试的mp4文件提供一下

这个文件 
https://github.com/chthomos/video-media-samples/raw/master/big-buck-bunny-1080p-30sec.mp4

**Comment by yapingcat** [comment]
更新到最新版本，再试一下

**Comment by Mr3h1v** [comment]
新版本问题修复了。
