### ISSUE TITLE
ts转mp4崩溃，panic: OUT OF RANGE

### ISSUE THREAD

**Issue by orestonce** [yapingcat/gomedia#146]
源代码：https://github.com/yapingcat/gomedia/blob/main/example/example_convert_ts_to_mp4.go
ts文件 [simple-ts.zip](https://github.com/user-attachments/files/16705715/simple-ts.zip)

```
go run example_convert_ts_to_mp4.go /root/d/input/simple-ts.ts 
read 8017824 size
panic: OUT OF RANGE

goroutine 1 [running]:
github.com/yapingcat/gomedia/go-codec.(*BitStream).GetBit(...)
        /root/d/gomedia/go-codec/bitstream.go:90
github.com/yapingcat/gomedia/go-codec.(*BitStream).ReadUE(0x18?)
        /root/d/gomedia/go-codec/bitstream.go:152 +0xe5
github.com/yapingcat/gomedia/go-codec.(*H264HrdParameters).Decode(0xc0001e96f8, 0xc0001e9760)
        /root/d/gomedia/go-codec/h264.go:569 +0xda
github.com/yapingcat/gomedia/go-codec.(*H264VuiParameters).Decode(0xc0001e9690, 0xc0001e9760)
        /root/d/gomedia/go-codec/h264.go:537 +0x265
github.com/yapingcat/gomedia/go-codec.(*SPS).Decode(0xc0000785c0, 0xc000078760)
        /root/d/gomedia/go-codec/h264.go:143 +0x85d
github.com/yapingcat/gomedia/go-codec.GetH264Resolution({0xc00001a0f0, 0x2a, 0x2a})
        /root/d/gomedia/go-codec/h264.go:252 +0x105
github.com/yapingcat/gomedia/go-mp4.(*mp4track).writeH264.func1({0xc000200006, 0x2a, 0x35ffa})
        /root/d/gomedia/go-mp4/mp4track.go:315 +0x269
github.com/yapingcat/gomedia/go-codec.SplitFrameWithStartCode({0xc000200006, 0x2c7d9, 0x35ffa}, 0xc0001e9928)
        /root/d/gomedia/go-codec/util.go:66 +0xd4
github.com/yapingcat/gomedia/go-mp4.(*mp4track).writeH264(0x462e94?, {0xc000200006?, 0x4d2b60?, 0x1?}, 0x6886ec7ff4329453?, 0xc0000b0600?)
        /root/d/gomedia/go-mp4/mp4track.go:301 +0x85
github.com/yapingcat/gomedia/go-mp4.(*mp4track).writeSample(0x4c7d40?, {0xc000200006?, 0xc000000001?, 0xc000000001?}, 0x6?, 0xc0001e0000?)
        /root/d/gomedia/go-mp4/mp4track.go:281 +0x47
github.com/yapingcat/gomedia/go-mp4.(*Movmuxer).Write(0xc000108000, 0x1?, {0xc000200006, 0x2c7d9, 0x35ffa}, 0xf250, 0xf22f)
        /root/d/gomedia/go-mp4/mp4muxer.go:166 +0x6f
main.main.func1(0xc000200000?, {0xc000200006, 0x2c7d9, 0x35ffa}, 0xf250, 0xf22f)
        /root/d/gomedia/example/example_convert_ts_to_mp4.go:48 +0xdd
github.com/yapingcat/gomedia/go-mpeg2.(*TSDemuxer).splitH264Frame(0xc0001e9e18, 0xc000014060)
        /root/d/gomedia/go-mpeg2/ts-demuxer.go:310 +0x2b2
github.com/yapingcat/gomedia/go-mpeg2.(*TSDemuxer).doVideoPesPacket(0xc000078e18, 0xc000014060, 0x28?)
        /root/d/gomedia/go-mpeg2/ts-demuxer.go:232 +0x19f
github.com/yapingcat/gomedia/go-mpeg2.(*TSDemuxer).Input(0xc0001e9e18, {0x50aa28, 0xc000106060})
        /root/d/gomedia/go-mpeg2/ts-demuxer.go:136 +0x92c
main.main()
        /root/d/gomedia/example/example_convert_ts_to_mp4.go:75 +0x465
exit status 2

```

**Comment by yapingcat** [comment]
最新版本解决了，感谢

**Comment by yapingcat** [comment]
https://github.com/yapingcat/gomedia/pull/136
这个mr 引入的问题

**Comment by orestonce** [comment]
赞，已经测试修复效果。
