### ISSUE TITLE
mp4muxer  Writetrailer() error

### ISSUE THREAD

**Issue by ljl8521** [yapingcat/gomedia#7]
muxer.Writetrailer() 后包报错， stbl-box.go中copy时未判断切片边界
panic: runtime error: slice bounds out of range [9229:9185]

goroutine 656 [running]:
github.com/yapingcat/gomedia/mp4.makeStblBox(0xc00018d800)
	/home/lnct/go/pkg/mod/github.com/yapingcat/gomedia/mp4@v0.0.0-20220113141621-ed8e583147fc/stbl-box.go:39 +0x4f8
github.com/yapingcat/gomedia/mp4.makeMinfBox(0xc00018d800)
	/home/lnct/go/pkg/mod/github.com/yapingcat/gomedia/mp4@v0.0.0-20220113141621-ed8e583147fc/minf-box.go:20 +0x7e
github.com/yapingcat/gomedia/mp4.makeMdiaBox(0xc00018d800)
	/home/lnct/go/pkg/mod/github.com/yapingcat/gomedia/mp4@v0.0.0-20220113141621-ed8e583147fc/mdia-box.go:6 +0xdc
github.com/yapingcat/gomedia/mp4.makeTrak(0x15e7800000002)
	/home/lnct/go/pkg/mod/github.com/yapingcat/gomedia/mp4@v0.0.0-20220113141621-ed8e583147fc/trak-box.go:7 +0x59
github.com/yapingcat/gomedia/mp4.(*Movmuxer).Writetrailer(0xc000311320)
	/home/lnct/go/pkg/mod/github.com/yapingcat/gomedia/mp4@v0.0.0-20220113141621-ed8e583147fc/mp4muxer.go:337 +0x39f

**Comment by yapingcat** [comment]
1.使用场景是什么

2.能上传一下测试文件吗，可以让我复现这个问题

**Comment by ljl8521** [comment]
1.&nbsp; 使用场景是多个摄像头的拉流显示，定时录像存储。
2.&nbsp; 偶发性的动态过程，比较难复现，我跑了12个小时，只panic了一次。代码看上去是切片边界值不对， 估计是offset增加超过了整个切片长度。





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Son ***@***.***&gt;; 
发送时间: 2022年6月10日(星期五) 中午11:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yapingcat/gomedia] mp4muxer  Writetrailer() error (Issue #7)





 
1.使用场景是什么
 
2.能上传一下测试文件吗，可以让我复现这个问题

**Comment by yapingcat** [comment]
你们生成的mp4文件多大的， 会超过4G吗？

**Comment by yapingcat** [comment]
我这边怀疑是mp4文件太大，导致了这个问题
你那边能尝试测试 “长时间录像，让mp4文件大于4GB” 这个场景吗？

**Comment by yapingcat** [comment]
我晚上尝试复现一下

**Comment by ljl8521** [comment]
不会，我拉取的子码流，存储时长半分钟，大小在2M左右。报错前打印出的muxer对象，感觉正常的。
????????定时器完成,停止存储
&amp;{0xc000cac080 2 40 map[1:0xc000c66f00] 0 640 360}
&amp;{0xc0002b6058 2 40 map[1:0xc000b2f020] 0 640 360}
panic: runtime error: slice bounds out of range [9229:9185]




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Son ***@***.***&gt;; 
发送时间: 2022年6月10日(星期五) 中午11:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yapingcat/gomedia] mp4muxer  Writetrailer() error (Issue #7)





 
你们生成的mp4文件多大的， 会超过4G吗？

**Comment by yapingcat** [comment]
hello,需要你帮个忙，能否在 stbl-box.go 文件中 ，这行 “offset, stblbox := STBL.Encode()” 代码之后 
加入以下代码
```golang
	if offset+len(stsdbox)+len(sttsbox)+len(cttsbox)+len(stscbox)+len(stszbox)+len(stcobox) > len(stblbox) {
		crash_log := fmt.Sprintf("%d %d %d %d %d %d %d %d %d %d", offset, len(stblbox),
			len(stsdbox), len(sttsbox), len(cttsbox), len(stscbox), len(stszbox), len(stcobox),
			track.stbltable.stsz.sampleCount, track.stbltable.stsc.entryCount)
		panic("out of range " + crash_log)
	}
```

**Comment by orestonce** [comment]
搞个文件把原始数据储存起来，以便触发的时候可以多次复现吧

**Comment by yapingcat** [comment]
@[ljl8521](https://github.com/ljl8521)
你是不是起了多个协程在做录像下载？

**Comment by yapingcat** [comment]
问题现象我这边已经复现
<img width="951" alt="企业微信截图_825e33ed-1694-478d-b9b8-f3b408173509" src="https://user-images.githubusercontent.com/32125710/173177288-e502b921-a367-4d54-8572-c7a233903372.png">

1. 如何复现
    开多个协程，每个协程读取不同的视频文件，然后转mp4文
2. 问题原因
    STBL 是全局变量，线程不安全，设置的Size值会被其他协程复写掉

复现代码

````golang
package main
import (
	"fmt"
	"io/ioutil"
	"math/rand"
	"os"
	"sync"
	"time"

	"github.com/yapingcat/gomedia/mp4"
	"github.com/yapingcat/gomedia/mpeg2"
)
type mymp4writer struct {
	fp *os.File
}

func newmymp4writer(f *os.File) *mymp4writer {
	return &mymp4writer{
		fp: f,
	}
}
func (mp4w *mymp4writer) Write(p []byte) (n int, err error) {
	return mp4w.fp.Write(p)
}
func (mp4w *mymp4writer) Seek(offset int64, whence int) (int64, error) {
	return mp4w.fp.Seek(offset, whence)
}
func (mp4w *mymp4writer) Tell() (offset int64) {
	offset, _ = mp4w.fp.Seek(0, 1)
	return
}
func main() {
	tsfile := "demo.ts"
	tsfile2 := "dome2.ts"
	ready := make(chan struct{})
	rand.Seed(time.Now().UnixNano())
	var wg sync.WaitGroup
	for i := 0; i < 30; i++ {
		wg.Add(1)
		go func(i int) {
			mp4filename := fmt.Sprintf("test20_%d.mp4", i)
			mp4file, err := os.OpenFile(mp4filename, os.O_CREATE|os.O_RDWR, 0666)
			if err != nil {
				fmt.Println(err)
				return
			}
			defer mp4file.Close()
			muxer := mp4.CreateMp4Muxer(newmymp4writer(mp4file))
			vtid := muxer.AddVideoTrack(mp4.MP4_CODEC_H264)
			var buf []byte
			if rand.Int()%2 == 0 {
				buf, err = ioutil.ReadFile(tsfile)
			} else {
				buf, err = ioutil.ReadFile(tsfile2)
			}
			if err != nil {
				panic(err)
			}
			fmt.Printf("read %d size\n", len(buf))
			demuxer := mpeg2.NewTSDemuxer()
			demuxer.OnFrame = func(cid mpeg2.TS_STREAM_TYPE, frame []byte, pts uint64, dts uint64) {
				if cid == mpeg2.TS_STREAM_H264 {
					err = muxer.Write(vtid, frame, uint64(pts), uint64(dts))
					if err != nil {
						panic(err)
					}
				}
			}

			err = demuxer.Input(buf)
			if err != nil {
				panic(err)
			}
			demuxer.Flush()
			wg.Done()
			<-ready
			fmt.Println("write trailer")
			err = muxer.Writetrailer()
			if err != nil {
				panic(err)
			}
		}(i)
	}
	wg.Wait()
	close(ready)
	time.Sleep(time.Minute)
}
````

**Comment by yapingcat** [comment]
fix bug c1cc7b0

请更新到最新的版本测试

**Comment by ljl8521** [comment]
是的，我是起了多个协程在进行文件存储，今天我更新一下最新版本测试一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yapingcat/gomedia"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月12日(星期天) 晚上8:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yapingcat/gomedia] mp4muxer  Writetrailer() error (Issue #7)





 
fix bug c1cc7b0
 
请更新到最新的版本测试

**Comment by yapingcat** [comment]
> 
可能是码流中没有sps，pps
崩溃之后 应该有残留在磁盘上的mp4 文件吧，能把这个发给我看一下吗

**Comment by ljl8521** [comment]
应该是视频还没稳定建立，就结束保存录像了，出问题的是个nvr设备，网络原因，建立连接比较慢。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yapingcat/gomedia"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月14日(星期二) 下午2:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yapingcat/gomedia] mp4muxer  Writetrailer() error (Issue #7)





   
可能是码流中没有sps，pps
 崩溃之后 应该有残留在磁盘上的mp4 文件吧，能把这个发给我看一下吗

**Comment by yapingcat** [comment]
没有sps/pps 导致panic，我找个时间修复了一下

**Comment by yapingcat** [comment]
最新的版本已经修复了 "没有sps/pps 导致panic“ ，请更新测试

由于最近版本改动较多，下面做一点说明

- mp4库有接口相关改动，具体使用可以参考example_covert_flv_to_mp4.go, 总的来说让使用更加简单了

- 调整 go.mod文件，每个子目录的go.mod 已经被删除，增加了项目目录下的go.mod 文件。
   请使用` go get github.com/yapingcat/gomedia` 更新到最新版本

**Comment by ljl8521** [comment]
测试2天，未出现"没有sps/pps 导致panic“，谢谢！



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yapingcat/gomedia"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月18日(星期六) 下午4:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yapingcat/gomedia] mp4muxer  Writetrailer() error (Issue #7)





 
最新的版本已经修复了 "没有sps/pps 导致panic“ ，请更新测试
 
由于最近版本改动较多，下面做一点说明
  
 
mp4库有接口相关改动，具体使用可以参考example_covert_flv_to_mp4.go, 总的来说让使用更加简单了
 
 
 
调整 go.mod文件，每个子目录的go.mod 已经被删除，增加了项目目录下的go.mod 文件。
 请使用 go get github.com/yapingcat/gomedia 更新到最新版本
